### ISSUE TITLE
BUG - person_campaign_flow cannot run with non-numeric records in 'property_value' klaviyo field

### ISSUE THREAD

**Issue by MisterClean** [fivetran/dbt_klaviyo#17]
**Are you a current Fivetran customer?** 

Yes, Copper Cow Coffee

**Describe the bug**

Package throws error when I run `models/klaviyo__person_campaign_flow.sql`. The fivetran package expects numeric_value of type numeric, but our klayvio event data contains events with non-numeric property values. This can be remedied in the staging model with a safe cast to drop non-numeric values.

**Steps to reproduce**
1. Implement an event in Klayvio with a non-numeric 'property_value' eg 'example.com/?test=123'
2. Build klaviyo events model

**Expected behavior**

The 'numeric_value' field  (originally 'property_value' from klaviyo) should be cast to numeric in order to return the proper revenue total.

**Project variables configuration**

```yml

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'coppercow_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    # Applies to all files under models/example/
    example:
      materialized: view

vars:
  klaviyo: # case insensitive 
    klaviyo__count_metrics: 
      - 'Active on Site'
      - 'Ordered Product'
      - 'Placed Order'
      - 'Refunded Order'

    klaviyo__sum_revenue_metrics:
      - 'Refunded Order'
      - 'Placed Order'
      - 'Ordered Product'
      - 'checkout started'
      - 'cancelled order'

```

**Package Version**

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.1
  - package: dbt-labs/audit_helper
    version: 0.5.0
  - package: fivetran/klaviyo_source
    version: [">=0.4.1", "<0.5.0"]
  - package: fivetran/klaviyo
    version: 0.4.0
```

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 
Error:
`07:12:46  7 of 25 ERROR creating table model dbt_mmclean_klaviyo.klaviyo__person_campaign_flow [ERROR in 1.47s]
Database Error in model klaviyo__person_campaign_flow (models/klaviyo__person_campaign_flow.sql)
  No matching signature for operator CASE; all THEN/ELSE arguments must be coercible to a common type but found: INT64, STRING; actual argument types (WHEN THEN) ELSE: (BOOL STRING) INT64 at [29:11]
  compiled SQL at target/run/klaviyo/models/klaviyo__person_campaign_flow.sql`

**Please indicate the level of urgency** 

Low

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
