### ISSUE TITLE
BUG - Duplicate row detected during DML action

### ISSUE THREAD

**Issue by bfockler** [fivetran/dbt_klaviyo#4]
**Are you a current Fivetran customer?** 
Yes

**Describe the bug**
Using the default Fivetran <-> Klaviyo connector and this package is resulting in the following error message:
```
Database Error in model klaviyo__events (models/klaviyo__events.sql)
  100090 (42P18): Duplicate row detected during DML action
```

**Expected behavior**

Create model with no errors

**Package Version**

```yml
  - package: fivetran/klaviyo_source
    version: 0.1.1
  - package: fivetran/klaviyo
    version: 0.1.1
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 
This didn't happen on the first dbt run, only the scheduled ones after it.

**Please indicate the level of urgency** 

Just testing for the first time

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @bfockler for opening this issue.

After some quick searching on dbt slack it seems that the error message you are receiving is due to an issue regarding the incremental unique key within `klaviyo__events` not being unique after subsequent incremental runs. This is why it most likely succeeded on your first run, but not on the following runs.

Our team will look into this issue and respond here when we have assigned and planned this bug fix effort.

**Comment by fivetran-jamie** [comment]
hey @bfockler could you try re-running after installing this branch? thinking [this](https://docs.getdbt.com/reference/resource-configs/snowflake-configs#merge-behavior-incremental-models) might do the trick

```yml
# packages.yml
  - git: https://github.com/fivetran/dbt_klaviyo.git
    revision: jr_working
```
