### ISSUE TITLE
[Feature] Passthrough Dagster asset_key to sources

### ISSUE THREAD

**Issue by irmacorado** [fivetran/dbt_klaviyo#48]
### Is there an existing feature request for this?

- [x] I have searched the existing issues

### Describe the Feature

In order to setup individual pipelines and schedules in Dagster for each Fivetran connector and their corresponding dbt models, you need pass the Fivetran `asset_key` to its corresponding source in the source yml file (`src_klaviyo.yml`)

### How would you implement this feature?

in my `dbt_project.yml`
```
vars:
...
    campaign_asset_key: your_asset_key
    event_asset_key: your_asset_key
    flow_asset_key: your_asset_key
    metric_asset_key: your_asset_key
    person_asset_key: your_asset_key
```

`src_klaviyo.yml`
```
version: 2

sources:

  - name: klaviyo

    tables:

      - name: campaign
        meta:
          dagster:
            asset_key: "{{ var('campaign_asset_key') }}"
...
```

### Are you interested in contributing this feature?

- [x] Yes.
- [x] Yes, but I will need assistance.
- [ ] No.

### Anything else?

https://blog.rittmananalytics.com/unlocking-data-orchestration-how-to-orchestrate-fivetran-and-dbt-with-dagster-eb03eb973dee#:~:text=Step%206%3A%20Managing%20Dependencies
